project_id = "ryehkycxyhdpufigcotc"

[functions.create-upi-booking]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.update-payment-status]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false
