project_id = "ryehkycxyhdpufigcotc"

[functions.send-booking-telegram]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.setup-telegram-webhook]
verify_jwt = false

[functions.check-stale-payments]
verify_jwt = false
